jumpstart/urls.py
"""

The **jumpstart.urls.py*** is the main URL Configuration, which includes the general URL patterns

**URL Patterns:**
    * ``url(r'^$', 'jumpstart.views.home', name='home')``
        This redirects to the Home Page
    * ``url(r'^admin/', include(admin.site.urls))``
        for the admin site
    * ``url(r'^login/$', 'jumpstart.views.login', name="login")``
        Redirects to the Login view
    * ``url(r'^logout/$', 'jumpstart.views.logout', name="logout")``
        Redirects to the Logout view
    * ``url(r'^projects/', include("projects.urls"))``
        Links the URL patterns configured in the Projects module
    * ``url(r'^settings/', include("profiles.urls", namespace="profiles"))``
        Links the URL patterns configures in the Profiles module
    * ``url(r'^wiki/home', 'jumpstart.views.view_wiki', name = 'wiki')``
        Redirects to the Mezzanine-powered Wiki Home Page
    * ``url(r'^', include("mezzanine.urls"))``
        Links the URL patterns provided by Mezzanine

"""
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.utils.functional import curry
from django.views.defaults import *

from mezzanine.core.views import direct_to_template
#from jumpstart import settings


admin.autodiscover()

handler500 = curry(server_error, template_name='error500.html')
handler404 = curry(page_not_found, template_name='error404.html')
handler403 = curry(permission_denied, template_name='error403.html')
 
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'jumpstart.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    # Change the admin prefix here to use an alternate URL for the
    # admin interface, which would be marginally more secure.
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'jumpstart.views.home', name='home'),
    url(r'^login/$', 'jumpstart.views.login', name="login"),
    url(r'^logout/$', 'jumpstart.views.logout', name="logout"),
    url(r'^clone/$', 'jumpstart.utils.clone_template', name="clone_template"),
    url(r'^error/$', 'jumpstart.views.error', name="error"),
    url(r'^projects/', include("projects.urls")),
    url(r'^settings/', include("profiles.urls", namespace="profiles")),
    url(r'^wiki/home/$', 'jumpstart.views.wiki', name = 'wiki'),
    #url(r'^wiki/trial', 'mezzanine_utils.utils.get_path', name = 'get_path'),
    url(r'^', include("mezzanine.urls")),
    #url(r'^wiki/', direct_to_template, {"template": "index.html"}, name="wiki"),
)

profiles/urls.py
"""

The **profiles.urls.py*** files involves URL patterns, attached to the URL pattern settings/

**URL Patterns:**
	* ``url(r'^$', 'settings', name='settings')``
		Redirects to the page where the user can view the current settings
	* ``url(r'^edit/(?P<pk>[-_\w]+)$', 'settings_edit', name='settings_edit')``
		Redirects to the page where the user can update the current settings

"""
from django.conf.urls import patterns, include, url


urlpatterns = patterns('profiles.views',
	
    # Examples:
    # url(r'^$', 'jumpstart.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    
    url(r'^$', 'settings', name='settings'),
    url(r'^edit/(?P<pk>[-_\w]+)$', 'settings_edit', name='settings_edit'),

)

templates/base.html
<!doctype html>
<html lang="{{ LANGUAGE_CODE }}"{% if LANGUAGE_BIDI %} dir="rtl"{% endif %}>
{% load pages_tags mezzanine_tags i18n future staticfiles %}

<head>
<meta http-equiv="Content-type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="keywords" content="{% block meta_keywords %}{% endblock %}">
<meta name="description" content="{% block meta_description %}{% endblock %}">
<title>{% block meta_title %}{% endblock %}{% if settings.SITE_TITLE %} | {{ settings.SITE_TITLE }}{% endif %}</title>
<link rel="shortcut icon" href="{% static "img/favicon.ico" %}">

{% ifinstalled mezzanine.blog %}
<link rel="alternate" type="application/rss+xml" title="RSS" href="{% url "blog_post_feed" "rss" %}">
<link rel="alternate" type="application/atom+xml" title="Atom" href="{% url "blog_post_feed" "atom" %}">
{% endifinstalled %}

{% compress css %}
<link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
<link rel="stylesheet" href="{% static "css/mezzanine.css" %}">
<link rel="stylesheet" href="{% static "css/bootstrap-theme.css" %}">
{% if LANGUAGE_BIDI %}
<link rel="stylesheet" href="{% static "css/rtl.css" %}">
{% endif %}
{% ifinstalled cartridge.shop %}
<link rel="stylesheet" href="{% static "css/cartridge.css" %}">
{% if LANGUAGE_BIDI %}
<link rel="stylesheet" href="{% static "css/cartridge.rtl.css" %}">
{% endif %}
{% endifinstalled %}
{% block extra_css %}{% endblock %}
{% endcompress %}

{% compress js %}
<script src="{% static "mezzanine/js/"|add:settings.JQUERY_FILENAME %}"></script>
<script src="{% static "js/bootstrap.js" %}"></script>
<script src="{% static "js/bootstrap-extras.js" %}"></script>
{% block extra_js %}{% endblock %}
{% include "includes/footer_scripts.html" %}
{% endcompress %}

<!--[if lt IE 9]>
<script src="{% static "js/html5shiv.js" %}"></script>
<script src="{% static "js/respond.min.js" %}"></script>
<![endif]-->

{% block extra_head %}{% endblock %}
</head>

<body id="{% block body_id %}body{% endblock %}">

<div class="navbar navbar-default navbar-fixed-top" role="navigation">
<div class="container">
<div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">{% trans "Toggle Navigation" %}</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    {% if settings.SITE_TITLE %}<a class="navbar-brand" href="/">{{ settings.SITE_TITLE }}</a>{% endif %}
    {% if settings.SITE_TAGLINE %}<p class="navbar-text visible-lg">{{ settings.SITE_TAGLINE }}</p>{% endif %}
</div>
<div class="navbar-collapse collapse">
    {% search_form "all" %}
    {% page_menu "pages/menus/dropdown.html" %}
</div>
</div>
</div>

<div class="container">

{% nevercache %}
{% if messages %}
<div class="messages">
{% for message in messages %}
<div class="alert alert-dismissable alert-{{ message.tags }}" data-alert="alert">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    {{ message }}
</div>
{% endfor %}
</div>
{% endif %}
{% endnevercache %}

<h1>{% block title %}{% endblock %}</h1>

<ul class="breadcrumb">
{% spaceless %}
{% block breadcrumb_menu %}{% page_menu "pages/menus/breadcrumb.html" %}{% endblock %}
{% endspaceless %}
</ul>

</div>

<div class="container">
<div class="row">

<div class="col-md-2 left">
    {% block left_panel %}
    <div class="panel panel-default tree">{% page_menu "pages/menus/tree.html" %}</div>
    {% endblock %}
</div>

<div class="col-md-7 middle">
    {% block main %}{% endblock %}
</div>

<div class="col-md-3 right">
    {% nevercache %}
    {% include "includes/user_panel.html" %}
    {% endnevercache %}
    <div class="panel panel-default">
    <div class="panel-body">
    {% block right_panel %}
    {% ifinstalled mezzanine.twitter %}
    {% include "twitter/tweets.html" %}
    {% endifinstalled %}
    {% endblock %}
    </div>
    </div>
</div>

</div>
</div>

<footer>
<div class="container">
{% page_menu "pages/menus/footer.html" %}

<div class="row">
<p class="site-info text-center">
    {% trans "Powered by" %}
    <a href="http://mezzanine.jupo.org">Mezzanine</a>{% ifinstalled cartridge.shop %},
    <a href="http://cartridge.jupo.org">Cartridge</a>{% endifinstalled %}
    {% trans "and" %}
    <a href="http://www.djangoproject.com">Django</a>
    <span class="separator">|</span>
    {% trans "Theme by" %} <a target="_blank" href="http://getbootstrap.com">Bootstrap</a>
    {% ifinstalled mezzanine.mobile %}
    <span class="separator">|</span>
    <a href="{% url "set_device" "mobile" %}?next={{ request.path }}">{% trans "View Mobile Site" %}</a>
    {% endifinstalled %}
</p>
</div>
</div>
</footer>

</body>
</html>

templates/copyright.html
{% load staticfiles %}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="col-md-8">
                <small><span>Copyright © 2014 Ingenuity, <span> <img src="{% static "images/flag.png" %}" alt=""> Proudly engineered in Davao City, Philippines.</span> </span></small>
            </div>
            <div class="col-md-4">
                <p class="muted pull-right"></p>
            </div>
        </div>
    </div>
</div>

templates/error403.html
{% extends "site_base.html" %}

{% block page_header_title %}ERROR 403:<br>
<font size = 5>You don't have permission to access {{request.path}} on this server.</font>
{% endblock %}

{% block content %}

<h2><font size = 2><a href="javascript:history.go(-1)">GO BACK TO PREVIOUS PAGE</a></font></h2>

{% endblock %}

templates/error404.html
{% extends "site_base.html" %}

{% block page_header_title %}ERROR 404:<br>
<font size = 5>The page {{request.path}} you are trying to access does not exist.</font>
{% endblock %}

{% block content %}

<h2><font size = 2><a href="javascript:history.go(-1)">GO BACK TO PREVIOUS PAGE</a></font></h2>

{% endblock %}

templates/error500.html
{% extends "site_base.html" %}

{% block page_header_title %}ERROR 500:<br>
<font size =5>Internal Server Error</font>
{% endblock %}

{% block content %}

<h2><font size = 2><a href="javascript:history.go(-1)">GO BACK TO PREVIOUS PAGE</a></font></h2>

{% endblock %}

templates/footer.html
{% load staticfiles %}
<div class="container">    
    <div class="row">
        <div class="col-lg-12">
            <div class="col-md-4">
                <ul class="list-unstyled">
                    <li><strong>INGENUITY HQ</strong></li>
                    <li>&nbsp;</li>
                    <li>3rd Level, 1.18 Centron Building </li>
                    <li>Quirino Boulevard</li>
                    <li>Davao City, Philippines</li>
                </ul>
                <ul class="footer-icons list-unstyled">
                    <li><a href="https://www.facebook.com/pages/Ingenuity/203500326338255" id="facebook-icon">facebook</a></li>
                    <li><a href="http://www.linkedin.com/company/2803834" id="linked-icon">linkedin</a></li>
                    <li><a href="https://twitter.com/ingenuityph1" id="twitter-icon">twitter</a></li>
                </ul>
            </div>
            <div class="col-md-4">
                <ul class="list-unstyled">
                    <li><strong>CONTACT</strong></li>
                    <li>&nbsp;</li>
                    <li>hello@ingenuity.ph</li>
                    <li>Mobile: +63.9177235646</li>
                    <li>Phone: (6382) 282.4359</li>
                </ul>
            </div>
            <div class="col-md-4">
                <img src="{% static "images/logo_small.png" %}"/>
                <span>| engineering awesome</span>
                <div class="fb-like fb_iframe_widget" data-href="https://www.facebook.com/pages/Ingenuity/203500326338255" data-send="true" data-width="450" data-show-faces="true" data-font="segoe ui" data-colorscheme="dark" fb-xfbml-state="rendered" fb-iframe-plugin-query="app_id=361705160549198&amp;color_scheme=dark&amp;font=segoe%20ui&amp;href=https%3A%2F%2Fwww.facebook.com%2Fpages%2FIngenuity%2F203500326338255&amp;locale=en_US&amp;sdk=joey&amp;send=true&amp;show_faces=true&amp;width=450"><span style="vertical-align: bottom; width: 450px; height: 57px;"><iframe name="f1b90abb5c" width="450px" height="1000px" frameborder="0" allowtransparency="true" scrolling="no" title="fb:like Facebook Social Plugin" src="http://www.facebook.com/plugins/like.php?app_id=361705160549198&amp;channel=http%3A%2F%2Fstatic.ak.facebook.com%2Fconnect%2Fxd_arbiter%2FdgdTycPTSRj.js%3Fversion%3D40%23cb%3Df3fef4f4bc%26domain%3Dingenuity.ph%26origin%3Dhttp%253A%252F%252Fingenuity.ph%252Ff1e2d8c4a4%26relation%3Dparent.parent&amp;color_scheme=dark&amp;font=segoe%20ui&amp;href=https%3A%2F%2Fwww.facebook.com%2Fpages%2FIngenuity%2F203500326338255&amp;locale=en_US&amp;sdk=joey&amp;send=true&amp;show_faces=true&amp;width=450" class="" style="border: none; visibility: visible; width: 450px; height: 57px;"></iframe></span></div>
            </div>
        </div>
    </div>
</div>

templates/form_custom_radio_field.html
<div class="row">
    <div class="col-md-12">
        <div class="form-group {% if field.errors %}has-error{% endif %}">
            {% for option in options %}
                <div class="custom-radio">
                    <label>
                        <input type="radio" id="id_{{field_name}}_{{option.id}}" name="{{field_name}}" value="{{option.id}}" {% if option.id == field_value %}checked="checked"{% endif %} />
                        <span>
                            {{option.name}}<br/><small>{{option.description}}</small>
                        </span>
                    </label>
                </div>
            {% endfor %}                
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        {% if field.errors %}
            {% for error in field.errors %}
                <p class="text-danger">You must select a {{field_label}}.</p>
            {% endfor %}
        {% endif %}
    </div>
</div>

templates/form_field_edit.html
{% load project_extras %}
<div class="form-group {% if field.errors %}has-error{% endif %}">
    {% if not hide_label %}
        <label class="control-label" for="{{ field.id_for_label }}">{{ field.label }}{% if not field.field.required %} (Optional){% endif %}</label>
    {% endif %}
    {{ field | add_css:"form-control" }}
     {% if field.help_text %}
         <span class="help-block">
            <p>{{ field.help_text }}</p>
        </span>
    {% endif %}
    {% if field.errors %}
        {% for error in field.errors %}
            <p class="text-danger">{{ error|escape }}</p>
        {% endfor %}
    {% endif %}
</div>

templates/home.html
{% extends "site_base.html" %}

{% block head_title %}Home{% endblock %}

{% block nav_home_active %}
    class="active"
{% endblock %}

{% block jumbotron %}
    <div class="jumbotron">
        <h1><span class="text-overlay">{{ SITE_NAME }}</span></h1>
        <p><span class="text-overlay">Tired of the <em>repetitive and tedious manual process</em> just to setup a new project? <strong>{{ SITE_NAME }}</strong> is here to provide automation so you can immediately <strong><u>jump start</u></strong> to project development with just a few clicks! Ingenious, right? Try it out now!</span></p>
        {% if user.is_authenticated %}
        <p><a class="btn btn-primary btn-lg" href="{% url 'project_add' %}"><span class="glyphicon glyphicon-plus"></span> &nbsp; Create a Project</a></p>
        {% endif %}
    </div>
{% endblock %}

{% block page_header_container %}
{% endblock %}

{% block left_content %}
    <h3>Here's what <u>JumpStart</u> <strong>can do</strong> <em>for you:</em></h3>
    
    <br/>

    <h5>1. Create a <strong>new project</strong> and save its details in the database</h5>

    <div class="clear"></div>

    <blockquote>
        <small>Choose what type of project to ceate (mobile or web)</small>
        <small>Choose which template is to be applied to the web or mobile application created</small>
    </blockquote>
    
    <div class="clear"></div>

    <h5>2. Setup <strong>Project Repository</strong></h5>
    <blockquote>
        <small>Create project repository on Ingenuity's Bitbucket account (GIT)</small>
        <small>Push initial commits on project repository (Commits depend on what type of project: iOS, Django and etc.)</small>
    </blockquote>
    
    <div class="clear"></div>

    <h5>3. Setup <strong>Project Management Tool</strong> (Redmine or JIRA)</h5>
    <blockquote>
        <small>Create new spaces on Redmine or Ingenuity's JIRA account, depending on which PM Tool the project requires.</small>
    </blockquote>
    
    <div class="clear"></div>

    <h5>4. Create a <strong>Test Site</strong></h5>
    <blockquote>
        <small>Create project directory on Ingenuity's server.</small>
        <small>Create virtual environment for the project.</small>
        <small>Install packages or dependencies for the project.</small>
        <small>Create and assign sub-domain for the project.</small>
        <small>Create NGINX configuration file and restart server so test site would be up and running.</small>
    </blockquote>
{% endblock %}

{% block right_content %}
    {% include "latest_projects.html" %}
{% endblock %}

templates/index.html
{% extends "base.html" %}

templates/latest_projects.html
{% load project_extras %}

<!-- Recently Created Projects (All) -->
{% display_latest as latest_projects %}
{% with glyphicon_name="time" list_title="Recently Added Projects" %}
{% include "latest_projects_shortlist.html" %}
{% endwith %}

<!-- Recently Created Projects (Web) -->
{% display_latest_web as latest_projects %}
{% with glyphicon_name="globe" list_title="Recent Web Projects" %}
{% include "latest_projects_shortlist.html" %}
{% endwith %}

<!-- Recently Created Projects (Mobile) -->
{% display_latest_mobile as latest_projects %}
{% with glyphicon_name="phone" list_title="Recent Mobile Projects" %}
{% include "latest_projects_shortlist.html" %}
{% endwith %}

templates/login.html
{% extends "site_base.html" %}

{% block head_title %}Login{% endblock %}

{% block nav_login_active %}
    class="active"
{% endblock %}

{% block page_header_title %}Login{% endblock %}

{% block left_content %}
    <div class="row">
        <div class="col-md-6">
            <form action='./?next={{ form.redirect_to }}' method='post'>
                {% csrf_token %}
                <legend>Please login to continue</legend>
                {% with form.username as field %}
                {% include "form_field_edit.html" %}
                {% endwith %}

                {% with form.password as field %}
                {% include "form_field_edit.html" %}
                {% endwith %}
                <button type="submit" class="btn btn-primary">Login</button>
            </form>
        </div>
    </div>
{% endblock %}

{% block show_alert_messages %}
    {% if form.errors %}
        showErrorMessage("Wrong username and/or password.");
    {% endif %}
{% endblock %}

templates/site_base.html
{% load staticfiles %}
{% load url from future %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block head_title_base %}{% if SITE_NAME %}{{ SITE_NAME }} | {% endif %}{% block head_title %}{% endblock %}{% endblock %}</title>
        {% block viewport %}
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% endblock %}

        {% block style_base %}
            <!-- Bootstrap (Flatly) -->
            <link href="{% static "bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
            <link href="{% static "bootstrap/flatly/bootstrap.min.css" %}" rel="stylesheet">
            <!-- Overwrites -->
            <link rel="stylesheet" href="{% static "css/base.css" %}" type="text/css">
            {% block extra_style %}{% endblock %}
        {% endblock %}

        {% block html5shim %}
            <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
            <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
            <!--[if lt IE 9]>
              <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
              <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
            <![endif]-->
        {% endblock %}

        {% block extra_head_base %}
            {% block extra_head %}{% endblock %}
        {% endblock %}
    </head>
    <body class="{% block body_class %}{% endblock %}" id="{% block body_id %}{% endblock %}">
        <div id="loading_modal" class="modal fade" tabindex="-1" role="dialog" data-keyboard="false" data-backdrop="static">
            <div style="height:200px">
              <span id="spinner_center" style="position: absolute;display: block;top: 50%;left: 50%;"></span>
            </div>
        </div>

        <div class="{% block wrapper_class %}{% endblock %}">
            {% block topbar_base %}
            <div class="navbar navbar-default navbar-fixed-top" {% block navbar_class %}navbar-fixed-top{% endblock %}>
                <div class="container">
                    {% block topbar %}
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            {% block site_brand %}
                                <a class="navbar-brand" href="{% url "home" %}">
                                    <img src="{% static "images/logo.png" %}"/>
                                    <strong>{{ SITE_NAME }}</strong>
                                </a>
                            {% endblock %}
                        </div>
                        <div class="navbar-collapse collapse navbar-responsive-collapse">
                            {% block nav %}
                                <ul class="nav navbar-nav">
                                    {% block nav_left %}
                                    {% endblock %}
                                </ul>
                                <ul class="nav navbar-nav navbar-right">
                                    {% block nav_right %}
                                        <li id="tab_home" {% block nav_home_active %}{% endblock %}><a href="{% url 'home' %}"><span class="glyphicon glyphicon-home"></span> &nbsp; Home</a></li>
                                        {% if user.is_authenticated %}
                                        <li id="tab_projects" {% block nav_projects_active %}{% endblock %}><a href="{% url 'projects' %}"><span class="glyphicon glyphicon-th-list"></span> &nbsp; Projects</a></li>
                                        <li id="tab_settings" {% block nav_administration_active %}{% endblock %}><a href="{% url 'profiles:settings' %}"><span class="glyphicon glyphicon-cog"></span> &nbsp; Settings</a></li>
                                        {% endif %}
                                        <li id="tab_wiki" {% block nav_wiki_active %}{% endblock %}><a href="{% url 'wiki' %}"><span class="glyphicon glyphicon-info-sign"></span> &nbsp; Wiki</a></li>
                                        <li id="tab_login" {% block nav_login_active %}{% endblock %}>
                                            {% if user.is_authenticated %}
                                                <a href="{% url 'logout' %}"><span class="glyphicon glyphicon-lock"></span> &nbsp; Logout</a>
                                            {% else %}
                                                <a href="{% url 'login' %}"><span class="glyphicon glyphicon-lock"></span> &nbsp; Login</a>
                                            {% endif %}
                                        </li>
                                    {% endblock %}
                                </ul>
                            {% endblock %}
                        </div>
                    {% endblock %}
                </div>
            </div>
            {% endblock %}

            {% block body_base %}
                {% block jumbotron %}
                {% endblock %}
                <div class="container">
                    {% block body %}
                        {% block page_header_container %}
                            <div class="row">
                                {% block page_header %}
                                    <div class="col-md-12">
                                        <div class="page-header">
                                             <div class="row">
                                                <div class="col-md-8 page-header-title">
                                                    <h1><strong>{% block page_header_title %}{% endblock %}</strong></h1>
                                                </div>
                                                <div class="col-md-4 page-header-controls">
                                                    {% block page_header_controls %}
                                                    {% endblock %}
                                                </div>
                                            </div>
                                        </div>
                                        <hr/>
                                    </div>
                                {% endblock %}
                            </div>
                        {% endblock %}
                        {% block content_container %}
                            <div class="row">
                                {% block content %}
                                    <div class="col-md-8">
                                        {% block message_alert %}
                                            {% block alert_info %}
                                                <div id="alert_info" class="alert alert-dismissable alert-info alert-hidden">
                                                    <button type="button" class="close" data-dismiss="alert">×</button>
                                                    {% block alert_info_message %}
                                                        <span id="alert_info_message"></span>
                                                    {% endblock %}
                                                </div>
                                            {% endblock %}
                                            {% block alert_success %}
                                                <div id="alert_success" class="alert alert-dismissable alert-success alert-hidden">
                                                    <button type="button" class="close" data-dismiss="alert">×</button>
                                                    {% block alert_success_message %}
                                                        <span id="alert_success_message"></span>
                                                    {% endblock %}
                                                </div>
                                            {% endblock %}
                                            {% block alert_warn %}
                                                <div id="alert_warning" class="alert alert-dismissable alert-warning alert-hidden">
                                                    <button type="button" class="close" data-dismiss="alert">×</button>
                                                    {% block alert_warning_message %}
                                                        <span id="alert_warning_message"></span>
                                                    {% endblock %}
                                                </div>
                                            {% endblock %}
                                            {% block alert_danger %}
                                                <div id="alert_danger" class="alert alert-dismissable alert-danger alert-hidden">
                                                    <button type="button" class="close" data-dismiss="alert">×</button>
                                                    {% block alert_danger_message %}
                                                        <span id="alert_danger_message"></span>
                                                    {% endblock %}
                                                </div>
                                            {% endblock %}
                                        {% endblock %}
                                        {% block left_content %}
                                        {% endblock %}
                                    </div>
                                    <div class="col-md-4">
                                        {% block right_content %}
                                        {% endblock %}
                                    </div>
                                {% endblock %}
                            </div>
                        {% endblock %}
                    {% endblock %}
                </div>
            {% endblock %}
            {% block footer_base %}
                <footer class="container footer-container">
                    {% block footer %}
                        {% include 'footer.html' %}
                    {% endblock %}
                </footer>
                <div class="container copyright-section">
                    {% block copyright %}
                        {% include 'copyright.html' %}
                    {% endblock %}
                </div>
            {% endblock %}
        </div>

        {% block script_base %}
            <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
            <script src="{% block jquery_src %}{% static "js/jquery.js" %}{% endblock %}"></script>
            
            <!-- Bootstrap -->
            <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>

            <script src="{% static "js/spin.min.js" %}"></script>

            <!-- Base Scripts -->
            <script type="text/javascript">
                $(document).ready(function(){
                    <!-- Message Alerts Display -->
                    {% include "message_alerts.html" %}
                    {% block show_alert_messages %}
                    {% endblock %}

                    <!-- Put other base scripts here -->
                });

                $("form").submit(function() {
                    var opts = {
                      lines: 15, // The number of lines to draw
                      length: 40, // The length of each line
                      width: 15, // The line thickness
                      radius: 60, // The radius of the inner circle
                      corners: 1, // Corner roundness (0..1)
                      rotate: 0, // The rotation offset
                      direction: 1, // 1: clockwise, -1: counterclockwise
                      color: '#000', // #rgb or #rrggbb or array of colors
                      speed: 1, // Rounds per second
                      trail: 60, // Afterglow percentage
                      shadow: false, // Whether to render a shadow
                      hwaccel: false, // Whether to use hardware acceleration
                      className: 'spinner', // The CSS class to assign to the spinner
                      zIndex: 2e9, // The z-index (defaults to 2000000000)
                      top: 'auto', // Top position relative to parent in px
                      left:'auto' // Left position relative to parent in px
                    };

                    var target = document.getElementById('spinner_center');
                    var spinner = new Spinner(opts).spin(target);

                    $('#loading_modal').modal('show')
                });

            </script>

            {% block extra_script %}{% endblock %}
        {% endblock %}

        {% block extra_body_base %}
            {% block extra_body %}{% endblock %}
        {% endblock %}
    </body>
</html>